package com.example.demo.Models.Forms;

public class bookAppointment {
	private int uid; // will be automatically provided when booking appointment
	private String pname;
	private String patage;
	private Long pphone;
	private String dname;
	private String adate;
	private String atime;
	private String uemail; // will be automatically provided when booking appointment
	

	// things like Aid , Uid , Did , Atoken, Uemail will be autogenerated
	
	public String getUemail() {
		return this.uemail;
	}
	public void setUemail(String uemail) {
		this.uemail = uemail;
	}
	public int getUid() {
		return this.uid;
	}
	public void setUid(int uid) {
		this.uid = uid;
	}
	
	public String getPname() {
		return this.pname;
	}
	
	public void setPname(String pname) {
		this.pname = pname;
	}
	public String getPatage() {
		return this.patage;
	}
	public void setPatage(String patage) {
		this.patage = patage;
	}
	public Long getPphone() {
		return this.pphone;
	}
	public void setPphone(Long pphone) {
		this.pphone = pphone;
	}
	public String getDname() {
		return this.dname;
	}
	public void setDname(String dname) {
		this.dname = dname;
	}
	public String getAdate() {
		return this.adate;
	}
	public void setAdate(String adate) {
		this.adate = adate;
	}
	public String getAtime() {
		return this.atime;
	}
	public void setAtime(String atime) {
		this.atime = atime;
	}
		
}
